apiVersion: v1
kind: ConfigMap
metadata:
  name: db-post-message-config
  namespace: production
  labels:
    app: db-post-message
data:
  POSTGRES_DB: db_post_message
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-post-message-pv-volume
  namespace: production
  labels:
    type: local
    app: db-post-message
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db-post-message"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: production
  name: db-post-message-pv-claim
  labels:
    app: db-post-message
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-post-message
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-post-message
  template:
    metadata:
      labels:
        app: db-post-message
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-post-message-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: db-post-message-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-post-message
  namespace: production
  labels:
    app: db-post-message
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: db-post-message