apiVersion: apps/v1
kind: Deployment
metadata:
  name: directmessageconsumer-app-dep
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: directmessageconsumer-app
  template:
    metadata:
      labels:
        app: directmessageconsumer-app
    spec:
      containers:
      - name: directmessageconsumer-app
        image: dockerfiles-directmessageconsumer_app
        imagePullPolicy: Never
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: directmessageconsumer-app-sev
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8089
    targetPort: 8089
  selector:
    app: directmessageconsumer-app
