apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-app-dep
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: follow-app
  template:
    metadata:
      labels:
        app: follow-app
    spec:
      containers:
      - name: follow-app
        image: dockerfiles-follow_app
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: follow-app-sev
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    app: follow-app
