apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-message-app-dep
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-message-app
  template:
    metadata:
      labels:
        app: post-message-app
    spec:
      containers:
      - name: post-message-app
        image: dockerfiles-post_message_app
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: post-message-app-sev
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: post-message-app
