apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app-dep
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-app
  template:
    metadata:
      labels:
        app: profile-app
    spec:
      containers:
      - name: profile-app
        image: dockerfiles-profile_app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: profile-app-sev
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: profile-app
