apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-app-dep
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-app
  template:
    metadata:
      labels:
        app: search-app
    spec:
      containers:
      - name: search-app
        image: dockerfiles-search_app
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: search-app-sev
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: search-app
