apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-app-dep
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timeline-app
  template:
    metadata:
      labels:
        app: timeline-app
    spec:
      containers:
      - name: timeline-app
        image: dockerfiles-timeline_app
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: timeline-app-sev
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: timeline-app
